if(NOT PNGCRUSH)
    find_program(PNGCRUSH pngcrush)
    if(PNGCRUSH)
        message(STATUS "pngcrush: ${PNGCRUSH} - found")
    else()
        message(WARNING "pngcrush - not found")
    endif()
endif()

function(makeTargetDirs)
	foreach(TargetFile ${ARGV})
		get_filename_component(TargetAbsPath ${TargetFile} PATH)
		if(TargetAbsPath)
			if(NOT IS_ABSOLUTE ${TargetAbsPath})
				set(TargetAbsPath ${CMAKE_CURRENT_BINARY_DIR}/${TargetAbsPath})
			endif()
			if(NOT EXISTS ${TargetAbsPath})
				file(MAKE_DIRECTORY ${TargetAbsPath})
			endif()
		endif()
	endforeach()
endfunction()
