if(NOT GXTEXCONV)
    find_program(GXTEXCONV gxtexconv)
    if(GXTEXCONV)
        message(STATUS "gxtexconv: ${GXTEXCONV} - found")
    else()
        message(FATAL_ERROR "gxtexconv - not found")
    endif()
endif()
if(NOT ELF2DOL)
    find_program(ELF2DOL elf2dol)
    if(ELF2DOL)
        message(STATUS "elf2dol: ${ELF2DOL} - found")
    else()
        message(FATAL_ERROR "elf2dol - not found")
    endif()
endif()
